import type { Metadata } from "next";
import "./normalize.css";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Particles = dynamic(
  () => import("@/components/ParticlesBackgrounds/animationBackground")
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Particles />
        <Header />
        {children}
      </body>
    </html>
  );
}
